In [1]:
1+1

2

In [3]:
import csv

# Ouverture du fichier en mode lecture ('r')
with open('produits.csv', mode='r', encoding='utf-8') as fichier:
    # Création du lecteur CSV
    lecteur = csv.reader(fichier)
    
    # Lecture et affichage des 5 premières lignes
    compteur = 0
    for ligne in lecteur:
        print(ligne)
        compteur += 1
        if compteur >= 5:
            break

['id_produit', 'produit', 'categorie', 'prix_unitaire', 'stock']
['P001', 'Smartphone', 'Electronique', '60.14', '257']
['P002', 'Casque audio', 'Electronique', '305.65', '331']
['P003', 'Chargeur solaire', 'Electronique', '278.7', '52']
['P004', 'Batterie externe', 'Electronique', '285.82', '307']

In [4]:
import csv

# Liste des fichiers à analyser
fichiers_a_lire = ['produits.csv', 'ventes.csv']

for nom_fichier in fichiers_a_lire:
    with open(nom_fichier, mode='r', encoding='utf-8') as fichier:
        lecteur = csv.reader(fichier)
        
        # Extraire la première ligne (les en-têtes / colonnes)
        colonnes = next(lecteur)
        
        # Compter le reste des lignes (les données)
        nombre_de_lignes = sum(1 for ligne in lecteur)
        
        # Affichage du résultat
        print(f"Fichier  : {nom_fichier}")
        print(f"Lignes   : {nombre_de_lignes}")
        print(f"Colonnes : {', '.join(colonnes)}")
        print("-" * 50)

Fichier  : produits.csv
Lignes   : 20
Colonnes : id_produit, produit, categorie, prix_unitaire, stock
--------------------------------------------------
Fichier  : ventes.csv
Lignes   : 200
Colonnes : id_vente, id_produit, pays, canal, quantite, montant, statut, mois
--------------------------------------------------

In [1]:
import pandas as pd

In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.1.0-cp312-cp312-win_amd64.whl.metadata (18 kB)
Collecting numpy>=2.0.2 (from pandas)
  Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\users\hp\venv-m01\lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in c:\users\hp\venv-m01\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.6 in c:\users\hp\venv-m01\lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp312-cp312-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.7 MB 364.6 kB/s eta 0:00:29
   - -------------------------------------- 0.5/10.7 MB 364.6 kB/s eta 0:00:29
   - -------------------------------------- 0.5/10.7 MB 364.6 kB/s eta 0:00:29
   - -------------------------------------- 0.5/10.7 MB 364.6 kB/s eta 0:00:29
   -- ------------------------------------- 0.8/10.7 MB 372.6 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/10.7 MB 372.6 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/10.7 MB 372.6 kB/s eta 0:00:27
   --- ------------------------------------ 1.0/10.7 MB 375.6 kB/s eta 0:00:26
   --- ------------------------------------ 1.0/10.7 MB 375.6 kB/s eta 0:00:26
   --- ------------------------------------ 1.0/10.7 MB 375.6 kB/s eta 0:00:26
   ---- ----------------------------------- 1.3/10.7 MB 379.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.7 MB 379.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.7 MB 379.1 kB/s eta 0:00:25
   ---- ----------------------------------- 1.3/10.7 MB 379.1 kB/s eta 0:00:25
   ----- ---------------------------------- 1.6/10.7 MB 376.1 kB/s eta 0:00:25
   ----- ---------------------------------- 1.6/10.7 MB 376.1 kB/s eta 0:00:25
   ----- ---------------------------------- 1.6/10.7 MB 376.1 kB/s eta 0:00:25
   ------ --------------------------------- 1.8/10.7 MB 378.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.7 MB 378.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.7 MB 378.4 kB/s eta 0:00:24
   ------ --------------------------------- 1.8/10.7 MB 378.4 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.7 MB 367.0 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.7 MB 367.0 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.7 MB 367.0 kB/s eta 0:00:24
   ------- -------------------------------- 2.1/10.7 MB 367.0 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.7 MB 355.0 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.7 MB 355.0 kB/s eta 0:00:24
   -------- ------------------------------- 2.4/10.7 MB 355.0 kB/s eta 0:00:24
   --------- ------------------------------ 2.6/10.7 MB 356.9 kB/s eta 0:00:23
   --------- ------------------------------ 2.6/10.7 MB 356.9 kB/s eta 0:00:23
   --------- ------------------------------ 2.6/10.7 MB 356.9 kB/s eta 0:00:23
   --------- ------------------------------ 2.6/10.7 MB 356.9 kB/s eta 0:00:23
   ---------- ----------------------------- 2.9/10.7 MB 356.9 kB/s eta 0:00:23
   ---------- ----------------------------- 2.9/10.7 MB 356.9 kB/s eta 0:00:23
   ---------- ----------------------------- 2.9/10.7 MB 356.9 kB/s eta 0:00:23
   ---------- ----------------------------- 2.9/10.7 MB 356.9 kB/s eta 0:00:23
   ----------- ---------------------------- 3.1/10.7 MB 350.8 kB/s eta 0:00:22
   ----------- ---------------------------- 3.1/10.7 MB 350.8 kB/s eta 0:00:22
   ----------- ---------------------------- 3.1/10.7 MB 350.8 kB/s eta 0:00:22
   ----------- ---------------------------- 3.1/10.7 MB 350.8 kB/s eta 0:00:22
   ------------ --------------------------- 3.4/10.7 MB 343.0 kB/s eta 0:00:22
   ------------ --------------------------- 3.4/10.7 MB 343.0 kB/s eta 0:00:22
   ------------ --------------------------- 3.4/10.7 MB 343.0 kB/s eta 0:00:22
   ------------ --------------------------- 3.4/10.7 MB 343.0 kB/s eta 0:00:22
   ------------ --------------------------- 3.4/10.7 MB 343.0 kB/s eta 0:00:22
   ------------- -------------------------- 3.7/10.7 MB 334.5 kB/s eta 0:00:22
   ------------- -------------------------- 3.7/10.7 MB 334.5 kB/s eta 0:00:22
   ------------- -------------------------- 3.7/10.7 MB 334.5 kB/s eta 0:00:22
   ------------- -------------------------- 3.7/10.7 MB 334.5 kB/s eta 0:00:22
   -------------- ------------------------- 3.9/10.7 MB 335.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.9/10.7 MB 335.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.9/10.7 MB 335.1 kB/s eta 0:00:21
   -------------- ------------------------- 3.9/10.7 MB 335.1 kB/s eta 0:00:21
   --------------- ------------------------ 4.2/10.7 MB 334.2 kB/s eta 0:00:20
   --------------- ------------------------ 4.2/10.7 MB 334.2 kB/s eta 0:00:20
   --------------- ------------------------ 4.2/10.7 MB 334.2 kB/s eta 0:00:20
   --------------- ------------------------ 4.2/10.7 MB 334.2 kB/s eta 0:00:20
   ---------------- ----------------------- 4.5/10.7 MB 329.8 kB/s eta 0:00:20
   ---------------- ----------------------- 4.5/10.7 MB 329.8 kB/s eta 0:00:20
   ---------------- ----------------------- 4.5/10.7 MB 329.8 kB/s eta 0:00:20
   ---------------- ----------------------- 4.5/10.7 MB 329.8 kB/s eta 0:00:20
   ----------------- ---------------------- 4.7/10.7 MB 329.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.7/10.7 MB 329.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.7/10.7 MB 329.7 kB/s eta 0:00:19
   ----------------- ---------------------- 4.7/10.7 MB 329.7 kB/s eta 0:00:19
   ------------------ --------------------- 5.0/10.7 MB 327.2 kB/s eta 0:00:18
   ------------------ --------------------- 5.0/10.7 MB 327.2 kB/s eta 0:00:18
   ------------------ --------------------- 5.0/10.7 MB 327.2 kB/s eta 0:00:18
   ------------------ --------------------- 5.0/10.7 MB 327.2 kB/s eta 0:00:18
   ------------------ --------------------- 5.0/10.7 MB 327.2 kB/s eta 0:00:18
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   ------------------- -------------------- 5.2/10.7 MB 324.3 kB/s eta 0:00:17
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   -------------------- ------------------- 5.5/10.7 MB 306.7 kB/s eta 0:00:18
   --------------------- ------------------ 5.8/10.7 MB 295.8 kB/s eta 0:00:17
   --------------------- ------------------ 5.8/10.7 MB 295.8 kB/s eta 0:00:17
   --------------------- ------------------ 5.8/10.7 MB 295.8 kB/s eta 0:00:17
   --------------------- ------------------ 5.8/10.7 MB 295.8 kB/s eta 0:00:17
   --------------------- ------------------ 5.8/10.7 MB 295.8 kB/s eta 0:00:17
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ---------------------- ----------------- 6.0/10.7 MB 295.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ----------------------- ---------------- 6.3/10.7 MB 286.0 kB/s eta 0:00:16
   ------------------------ --------------- 6.6/10.7 MB 280.2 kB/s eta 0:00:15
   ------------------------ --------------- 6.6/10.7 MB 280.2 kB/s eta 0:00:15
   ------------------------ --------------- 6.6/10.7 MB 280.2 kB/s eta 0:00:15
   ------------------------ --------------- 6.6/10.7 MB 280.2 kB/s eta 0:00:15
   ------------------------ --------------- 6.6/10.7 MB 280.2 kB/s eta 0:00:15
   ------------------------- -------------- 6.8/10.7 MB 278.3 kB/s eta 0:00:15
   ------------------------- -------------- 6.8/10.7 MB 278.3 kB/s eta 0:00:15
   ------------------------- -------------- 6.8/10.7 MB 278.3 kB/s eta 0:00:15
   ------------------------- -------------- 6.8/10.7 MB 278.3 kB/s eta 0:00:15
   ------------------------- -------------- 6.8/10.7 MB 278.3 kB/s eta 0:00:15
   ------------------------- -------------- 6.8/10.7 MB 278.3 kB/s eta 0:00:15
   -------------------------- ------------- 7.1/10.7 MB 274.2 kB/s eta 0:00:14
   -------------------------- ------------- 7.1/10.7 MB 274.2 kB/s eta 0:00:14
   -------------------------- ------------- 7.1/10.7 MB 274.2 kB/s eta 0:00:14
   -------------------------- ------------- 7.1/10.7 MB 274.2 kB/s eta 0:00:14
   --------------------------- ------------ 7.3/10.7 MB 273.9 kB/s eta 0:00:13
   --------------------------- ------------ 7.3/10.7 MB 273.9 kB/s eta 0:00:13
   --------------------------- ------------ 7.3/10.7 MB 273.9 kB/s eta 0:00:13
   ---------------------------- ----------- 7.6/10.7 MB 277.3 kB/s eta 0:00:12
   ---------------------------- ----------- 7.6/10.7 MB 277.3 kB/s eta 0:00:12
   ---------------------------- ----------- 7.6/10.7 MB 277.3 kB/s eta 0:00:12
   ---------------------------- ----------- 7.6/10.7 MB 277.3 kB/s eta 0:00:12
   ----------------------------- ---------- 7.9/10.7 MB 279.1 kB/s eta 0:00:11
   ----------------------------- ---------- 7.9/10.7 MB 279.1 kB/s eta 0:00:11
   ----------------------------- ---------- 7.9/10.7 MB 279.1 kB/s eta 0:00:11
   ------------------------------ --------- 8.1/10.7 MB 281.7 kB/s eta 0:00:10
   ------------------------------ --------- 8.1/10.7 MB 281.7 kB/s eta 0:00:10
   ------------------------------ --------- 8.1/10.7 MB 281.7 kB/s eta 0:00:10
   ------------------------------ --------- 8.1/10.7 MB 281.7 kB/s eta 0:00:10
   ------------------------------- -------- 8.4/10.7 MB 282.8 kB/s eta 0:00:09
   ------------------------------- -------- 8.4/10.7 MB 282.8 kB/s eta 0:00:09
   ------------------------------- -------- 8.4/10.7 MB 282.8 kB/s eta 0:00:09
   ------------------------------- -------- 8.4/10.7 MB 282.8 kB/s eta 0:00:09
   -------------------------------- ------- 8.7/10.7 MB 284.5 kB/s eta 0:00:08
   -------------------------------- ------- 8.7/10.7 MB 284.5 kB/s eta 0:00:08
   -------------------------------- ------- 8.7/10.7 MB 284.5 kB/s eta 0:00:08
   --------------------------------- ------ 8.9/10.7 MB 283.8 kB/s eta 0:00:07
   --------------------------------- ------ 8.9/10.7 MB 283.8 kB/s eta 0:00:07
   --------------------------------- ------ 8.9/10.7 MB 283.8 kB/s eta 0:00:07
   --------------------------------- ------ 8.9/10.7 MB 283.8 kB/s eta 0:00:07
   ---------------------------------- ----- 9.2/10.7 MB 282.4 kB/s eta 0:00:06
   ---------------------------------- ----- 9.2/10.7 MB 282.4 kB/s eta 0:00:06
   ---------------------------------- ----- 9.2/10.7 MB 282.4 kB/s eta 0:00:06
   ---------------------------------- ----- 9.2/10.7 MB 282.4 kB/s eta 0:00:06
   ----------------------------------- ---- 9.4/10.7 MB 281.7 kB/s eta 0:00:05
   ----------------------------------- ---- 9.4/10.7 MB 281.7 kB/s eta 0:00:05
   ----------------------------------- ---- 9.4/10.7 MB 281.7 kB/s eta 0:00:05
   ----------------------------------- ---- 9.4/10.7 MB 281.7 kB/s eta 0:00:05
   ------------------------------------ --- 9.7/10.7 MB 279.6 kB/s eta 0:00:04
   ------------------------------------ --- 9.7/10.7 MB 279.6 kB/s eta 0:00:04
   ------------------------------------ --- 9.7/10.7 MB 279.6 kB/s eta 0:00:04
   ------------------------------------ --- 9.7/10.7 MB 279.6 kB/s eta 0:00:04
   ------------------------------------ --- 9.7/10.7 MB 279.6 kB/s eta 0:00:04
   ------------------------------------- -- 10.0/10.7 MB 274.5 kB/s eta 0:00:03
   ------------------------------------- -- 10.0/10.7 MB 274.5 kB/s eta 0:00:03
   ------------------------------------- -- 10.0/10.7 MB 274.5 kB/s eta 0:00:03
   -------------------------------------- - 10.2/10.7 MB 275.6 kB/s eta 0:00:02
   -------------------------------------- - 10.2/10.7 MB 275.6 kB/s eta 0:00:02
   -------------------------------------- - 10.2/10.7 MB 275.6 kB/s eta 0:00:02
   -------------------------------------- - 10.2/10.7 MB 275.6 kB/s eta 0:00:02
   -------------------------------------- - 10.2/10.7 MB 275.6 kB/s eta 0:00:02
   ---------------------------------------  10.5/10.7 MB 274.2 kB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 274.2 kB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 274.2 kB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 274.2 kB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 274.2 kB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 274.2 kB/s eta 0:00:01
   ---------------------------------------  10.7/10.7 MB 267.4 kB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 265.2 kB/s eta 0:00:00
Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 364.6 kB/s eta 0:00:34
   - -------------------------------------- 0.5/12.6 MB 364.6 kB/s eta 0:00:34
   - -------------------------------------- 0.5/12.6 MB 364.6 kB/s eta 0:00:34
   - -------------------------------------- 0.5/12.6 MB 364.6 kB/s eta 0:00:34
   -- ------------------------------------- 0.8/12.6 MB 328.9 kB/s eta 0:00:36
   -- ------------------------------------- 0.8/12.6 MB 328.9 kB/s eta 0:00:36
   -- ------------------------------------- 0.8/12.6 MB 328.9 kB/s eta 0:00:36
   --- ------------------------------------ 1.0/12.6 MB 340.2 kB/s eta 0:00:34
   --- ------------------------------------ 1.0/12.6 MB 340.2 kB/s eta 0:00:34
   --- ------------------------------------ 1.0/12.6 MB 340.2 kB/s eta 0:00:34
   --- ------------------------------------ 1.0/12.6 MB 340.2 kB/s eta 0:00:34
   ---- ----------------------------------- 1.3/12.6 MB 349.5 kB/s eta 0:00:33
   ---- ----------------------------------- 1.3/12.6 MB 349.5 kB/s eta 0:00:33
   ---- ----------------------------------- 1.3/12.6 MB 349.5 kB/s eta 0:00:33
   ----- ---------------------------------- 1.6/12.6 MB 361.6 kB/s eta 0:00:31
   ----- ---------------------------------- 1.6/12.6 MB 361.6 kB/s eta 0:00:31
   ----- ---------------------------------- 1.6/12.6 MB 361.6 kB/s eta 0:00:31
   ----- ---------------------------------- 1.6/12.6 MB 361.6 kB/s eta 0:00:31
   ----- ---------------------------------- 1.8/12.6 MB 353.2 kB/s eta 0:00:31
   ----- ---------------------------------- 1.8/12.6 MB 353.2 kB/s eta 0:00:31
   ----- ---------------------------------- 1.8/12.6 MB 353.2 kB/s eta 0:00:31
   ------ --------------------------------- 2.1/12.6 MB 355.9 kB/s eta 0:00:30
   ------ --------------------------------- 2.1/12.6 MB 355.9 kB/s eta 0:00:30
   ------ --------------------------------- 2.1/12.6 MB 355.9 kB/s eta 0:00:30
   ------- -------------------------------- 2.4/12.6 MB 361.8 kB/s eta 0:00:29
   ------- -------------------------------- 2.4/12.6 MB 361.8 kB/s eta 0:00:29
   ------- -------------------------------- 2.4/12.6 MB 361.8 kB/s eta 0:00:29
   ------- -------------------------------- 2.4/12.6 MB 361.8 kB/s eta 0:00:29
   -------- ------------------------------- 2.6/12.6 MB 357.0 kB/s eta 0:00:28
   -------- ------------------------------- 2.6/12.6 MB 357.0 kB/s eta 0:00:28
   -------- ------------------------------- 2.6/12.6 MB 357.0 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   --------- ------------------------------ 2.9/12.6 MB 356.2 kB/s eta 0:00:28
   ---------- ----------------------------- 3.1/12.6 MB 323.8 kB/s eta 0:00:30
   ---------- ----------------------------- 3.1/12.6 MB 323.8 kB/s eta 0:00:30
   ---------- ----------------------------- 3.1/12.6 MB 323.8 kB/s eta 0:00:30
   ---------- ----------------------------- 3.4/12.6 MB 325.8 kB/s eta 0:00:29
   ---------- ----------------------------- 3.4/12.6 MB 325.8 kB/s eta 0:00:29
   ---------- ----------------------------- 3.4/12.6 MB 325.8 kB/s eta 0:00:29
   ---------- ----------------------------- 3.4/12.6 MB 325.8 kB/s eta 0:00:29
   ----------- ---------------------------- 3.7/12.6 MB 327.0 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.6 MB 327.0 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.6 MB 327.0 kB/s eta 0:00:28
   ----------- ---------------------------- 3.7/12.6 MB 327.0 kB/s eta 0:00:28
   ------------ --------------------------- 3.9/12.6 MB 328.5 kB/s eta 0:00:27
   ------------ --------------------------- 3.9/12.6 MB 328.5 kB/s eta 0:00:27
   ------------ --------------------------- 3.9/12.6 MB 328.5 kB/s eta 0:00:27
   ------------- -------------------------- 4.2/12.6 MB 329.4 kB/s eta 0:00:26
   ------------- -------------------------- 4.2/12.6 MB 329.4 kB/s eta 0:00:26
   ------------- -------------------------- 4.2/12.6 MB 329.4 kB/s eta 0:00:26
   ------------- -------------------------- 4.2/12.6 MB 329.4 kB/s eta 0:00:26
   -------------- ------------------------- 4.5/12.6 MB 331.8 kB/s eta 0:00:25

[notice] A new release of pip is available: 25.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# 1. Lecture des fichiers CSV
df_produits = pd.read_csv('produits.csv')
df_ventes = pd.read_csv('ventes.csv')

# 2. Création du tableau de synthèse
resume = pd.DataFrame({
    'Fichier': ['produits.csv', 'ventes.csv'],
    'Lignes': [len(df_produits), len(df_ventes)],
    'Colonnes': [
        ', '.join(df_produits.columns),
        ', '.join(df_ventes.columns)
    ]
})
pd.set_option('display.max_colwidth', None)

# 3. Affichage du résultat
resume

,Fichier,Lignes,Colonnes
0,produits.csv,20,"id_produit, produit, categorie, prix_unitaire, stock"
1,ventes.csv,200,"id_vente, id_produit, pays, canal, quantite, montant, statut, mois"

In [5]:
df_ventes.head()

  id_vente id_produit pays    canal  quantite  montant    statut  mois
0    V0001       P010   CI  desktop         4   170.84  expediee     2
1    V0002       P001   CM   mobile         6   360.84    livree     3
2    V0003       P018   SN   mobile         4    83.92  expediee     3
3    V0004       P016   SN   mobile         4    73.00    livree     2
4    V0005       P017   ML   mobile         5   155.90  expediee     1

In [1]:
17//5

3

In [2]:
17 % 5

2

In [3]:
len ("Savon noir".strip())

10

In [8]:
import pandas as pd

In [11]:
df_produits = pd.read_csv('produits.csv')

In [12]:
df_produits.head()

  id_produit           produit     categorie  prix_unitaire  stock
0       P001        Smartphone  Electronique          60.14    257
1       P002      Casque audio  Electronique         305.65    331
2       P003  Chargeur solaire  Electronique         278.70     52
3       P004  Batterie externe  Electronique         285.82    307
4       P005      Boubou brode          Mode          58.96    215

In [2]:
import pandas as pd

In [3]:
# Chargement des produits et des ventes
df_produits = pd.read_csv('produits.csv')
df_ventes = pd.read_csv('ventes.csv')

In [4]:
# Aperçu des 5 premières lignes des produits
df_produits.head()

  id_produit           produit     categorie  prix_unitaire  stock
0       P001        Smartphone  Electronique          60.14    257
1       P002      Casque audio  Electronique         305.65    331
2       P003  Chargeur solaire  Electronique         278.70     52
3       P004  Batterie externe  Electronique         285.82    307
4       P005      Boubou brode          Mode          58.96    215

In [5]:
# Informations techniques sur le tableau des ventes
df_ventes.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_vente    200 non-null    str
 1   id_produit  200 non-null    str
 2   pays        200 non-null    str
 3   canal       200 non-null    str
 4   quantite    200 non-null    int64
 5   montant     200 non-null    float64
 6   statut      200 non-null    str
 7   mois        200 non-null    int64
dtypes: float64(1), int64(2), str(5)
memory usage: 12.6 KB

In [6]:
df_ventes.describe()

         quantite      montant        mois
count  200.000000   200.000000  200.000000
mean     3.740000   284.739050    2.085000
std      1.710858   378.940014    0.813069
min      1.000000     4.470000    1.000000
25%      2.000000    72.285000    1.000000
50%      4.000000   133.980000    2.000000
75%      5.000000   353.760000    3.000000
max      6.000000  1833.900000    3.000000

In [7]:
df_ventes.to_csv('ventes_export.csv', index=False)

In [9]:
# Compter le nombre de doublons
print(df_ventes.duplicated().sum())

0

In [10]:
# Compter le nombre de valeurs manquantes par colonne
print(df_ventes.isna().sum())

id_vente      0
id_produit    0
pays          0
canal         0
quantite      0
montant       0
statut        0
mois          0
dtype: int64

In [11]:
# Vérifier si un id_vente est répété
df_ventes.duplicated(subset=['id_vente']).sum()

np.int64(0)

In [12]:
# Convertir la colonne pays en majuscules
df_ventes['pays'] = df_ventes['pays'].str.strip().str.upper()
df_ventes['pays'].unique()

<StringArray>
['CI', 'CM', 'SN', 'ML', 'MA']
Length: 5, dtype: str